on:
  push:
    branches:
      - main

name: Deploy
jobs:
  build:
    name: zola prod deploy
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@master
    - name: zola deploy
      uses: shalzz/zola-deploy-action@v0.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
